In [1]:
import pandas as pd

## Working with jsom

In [3]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [4]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-12,1783814401,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-12,1783814401,0.0384
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-12,1783814401,0.6860
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-12,1783814401,0.8610
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-12,1783814401,3.8500
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-12,1783814401,2.4900
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-12,1783814401,0.1710
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-12,1783814401,0.1900
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-12,1783814401,0.2800
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-12,1783814401,0.2800

## Working with sql

In [5]:
!pip install mysql.connector

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     - -------------------------------------- 0.5/11.9 MB 2.4 MB/s eta 0:00:05
     ---- ----------------------------------- 1.3/11.9 MB 2.7 MB/s eta 0:00:04
     ------ --------------------------------- 1.8/11.9 MB 2.9 MB/s eta 0:00:04
     ------- -------------------------------- 2.4/11.9 MB 2.8 MB/s eta 0:00:04
     --------- ------------------------------ 2.9/11.9 MB 2.8 MB/s eta 0:00:04
     ------------ --------------------------- 3.7/11.9 MB 2.8 MB/s eta 0:00:03
     -------------- ------------------------- 4.2/11.9 MB 2.8 MB/s eta 0:00:03
     --------------- ------------------------ 4.5/11.9 MB 2.7 MB/s eta 0:00:03
     --------------- ------------------------ 4.7/11.9 MB 2.5 MB/s eta 0:00:03
     ---------------- ----------------------- 5.0/11.9 MB 2.4 MB/s eta 0:00:03
     ------------------ --------------------- 5.5/11.9 MB 2.4 MB/s eta 0:00:03
     ------------------- -------------------- 5.8/11.9 MB 2.3 MB/s eta 0:00:03
     -------------------- ------------------- 6.0/11.9 MB 2.2 MB/s eta 0:00:03
     --------------------- ------------------ 6.3/11.9 MB 2.2 MB/s eta 0:00:03
     ---------------------- ----------------- 6.6/11.9 MB 2.2 MB/s eta 0:00:03
     ----------------------- ---------------- 7.1/11.9 MB 2.1 MB/s eta 0:00:03
     ------------------------ --------------- 7.3/11.9 MB 2.1 MB/s eta 0:00:03
     -------------------------- ------------- 7.9/11.9 MB 2.1 MB/s eta 0:00:02
     ----------------------------- ---------- 8.7/11.9 MB 2.2 MB/s eta 0:00:02
     ------------------------------ --------- 9.2/11.9 MB 2.2 MB/s eta 0:00:02
     ------------------------------- -------- 9.4/11.9 MB 2.2 MB/s eta 0:00:02
     --------------------------------- ------ 10.0/11.9 MB 2.2 MB/s eta 0:00:01
     ----------------------------------- ---- 10.5/11.9 MB 2.2 MB/s eta 0:00:01
     ------------------------------------- -- 11.0/11.9 MB 2.2 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 2.2 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 2.2 MB/s  0:00:05
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248050 sha256=6f08e28ccb33a39c7adc94c950b73b5ba3592f7f6a31cdf6c8323b1889a9aa43
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9